### ISSUE TITLE
Clarification of channel pagination.

### ISSUE THREAD

**Issue by xles** [radiodoc/uv-5r#40]
Feedback from Dave Knight, K2COE:

> Users with a lot of programmed channels might appreciate an annotation explaining that, beyond pressing the up/down arrow key many times:
>
> 1 - holding down the up/down arrow key will scan rapidly through the programmed channels, until the key is released
>
> 2 - simply entering the 3 digit channel number (start with 0 for channels lower than 100, e.g. "045") will select that channel directly.  Attempting to select a channel that has not been programmed emits a "beep".

**Comment by diemkae** [comment]
Outstanding; thank you very much!

Sorry to have "given up" so quickly on the toolchain thing, but since
retiring, I've somehow become busier that when I was working.  Fifty years
of working 10x7 on other people's projects, while being intensely curious
about numerous scientific endeavors, resulted in a substantial backlog of
"personal interest" projects being stashed on the back burner.  Now I am
blessed to be able to work on them.  Unfortunately, at the ripe old age of
73, I have come to understand that I have yet another deadline, and the
amount of work to be done tends to overwhelm the  resources at my
disposal.

Eleven years into "retirement", I've barely scratched the surface, in part
because new projects pique my interest almost every day!

Happy Easter!

Dave

On Sun, Mar 27, 2016 at 11:53 AM, xles McFuzzypants <
notifications@github.com> wrote:

> Closed #40 https://github.com/radiodoc/uv-5r/issues/40.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/radiodoc/uv-5r/issues/40#event-604523178

## 

The "Safe in Church" deception: believing that calling some building a
"sanctuary" will magically deter criminal violence is a dangerous delusion!

The "Gun-Free Zone" deception: believing that a "No Guns" policy or sign
will deter criminal violence is "magical thinking" in its most dangerous
form!

In your time of need, may your piece be with you!
